# Generated by Django 5.1.2 on 2024-10-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_delete_foodrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
